[workspace]
resolver = "2"
members = ["crates/*", "tests/contest/*", "tools/*"]
exclude = ["experiment/seccomp", "experiment/selinux"]

[profile.release]
lto = true

[patch.crates-io]
oci-spec = { git = "https://github.com/viboognesh/oci-spec-rs.git" }
